from __future__ import annotations

import base64
import json
import os
import secrets
import tomllib
from pathlib import Path

from pydantic import BaseModel, ConfigDict, Field

DEFAULT_CONFIG_PATH = Path("~/.config/mvp-orbit/config.toml").expanduser()
NODE_SHARED_CONFIG_PREFIX = "orbit-node:"
NODE_SHARED_CONFIG_VERSION = 1


class HubConfig(BaseModel):
    model_config = ConfigDict(extra="forbid")

    host: str = "127.0.0.1"
    port: int = 8080
    db: str = "./.orbit-hub/hub.sqlite3"
    object_root: str = "./.orbit-hub/objects"
    url: str | None = None

    def resolved_url(self) -> str:
        return self.url or f"http://{self.host}:{self.port}"


class AuthConfig(BaseModel):
    model_config = ConfigDict(extra="forbid")

    api_token: str | None = None


class AgentConfig(BaseModel):
    model_config = ConfigDict(extra="forbid")

    id: str | None = None
    workspace_root: str | None = None
    poll_interval_sec: float = 5.0
    heartbeat_interval_sec: float = 5.0


class OrbitConfig(BaseModel):
    model_config = ConfigDict(extra="forbid")

    hub: HubConfig = Field(default_factory=HubConfig)
    auth: AuthConfig = Field(default_factory=AuthConfig)
    agent: AgentConfig = Field(default_factory=AgentConfig)


def resolve_config_path(path: str | Path | None = None) -> Path:
    if path is None:
        path = os.getenv("ORBIT_CONFIG")
    if path is None:
        return DEFAULT_CONFIG_PATH
    return Path(path).expanduser()


def load_config(path: str | Path | None = None) -> tuple[Path, OrbitConfig]:
    resolved = resolve_config_path(path)
    if not resolved.exists():
        return resolved, OrbitConfig()
    payload = tomllib.loads(resolved.read_text(encoding="utf-8"))
    return resolved, OrbitConfig.model_validate(payload)


def save_config(config: OrbitConfig, path: str | Path | None = None) -> Path:
    resolved = resolve_config_path(path)
    resolved.parent.mkdir(parents=True, exist_ok=True)
    resolved.write_text(render_config(config), encoding="utf-8")
    try:
        os.chmod(resolved, 0o600)
    except OSError:
        pass
    return resolved


def ensure_hub_token(config: OrbitConfig) -> OrbitConfig:
    if not config.auth.api_token:
        config.auth.api_token = secrets.token_urlsafe(32)
    return config


def encode_node_shared_config(config: OrbitConfig) -> str:
    payload = {
        "version": NODE_SHARED_CONFIG_VERSION,
        "hub": {"url": config.hub.resolved_url()},
        "auth": {"api_token": config.auth.api_token},
    }
    if not payload["hub"]["url"] or not payload["auth"]["api_token"]:
        raise ValueError("cannot encode node shared config without hub.url and auth.api_token")
    encoded = base64.urlsafe_b64encode(
        json.dumps(payload, separators=(",", ":"), sort_keys=True).encode("utf-8")
    ).decode("ascii")
    return f"{NODE_SHARED_CONFIG_PREFIX}{encoded.rstrip('=')}"


def apply_node_shared_config(config: OrbitConfig, shared_config: str) -> OrbitConfig:
    if not shared_config.startswith(NODE_SHARED_CONFIG_PREFIX):
        raise ValueError(f"node shared config must start with {NODE_SHARED_CONFIG_PREFIX}")
    token = shared_config[len(NODE_SHARED_CONFIG_PREFIX) :]
    padding = "=" * (-len(token) % 4)
    try:
        payload = json.loads(base64.urlsafe_b64decode((token + padding).encode("ascii")).decode("utf-8"))
    except Exception as exc:  # pragma: no cover - defensive parsing
        raise ValueError("invalid node shared config encoding") from exc
    if payload.get("version") != NODE_SHARED_CONFIG_VERSION:
        raise ValueError(f"unsupported node shared config version: {payload.get('version')!r}")

    config.hub.url = HubConfig.model_validate(payload.get("hub") or {}).resolved_url()
    config.auth = AuthConfig.model_validate(payload.get("auth") or {})
    if not config.hub.url or not config.auth.api_token:
        raise ValueError("node shared config is missing required values")
    return config


def render_config(config: OrbitConfig) -> str:
    lines = [
        "# mvp-orbit configuration",
        "# Generated by `orbit init ...`.",
        "",
    ]
    sections = [
        ("hub", config.hub.model_dump(mode="json", exclude_none=True)),
        ("auth", config.auth.model_dump(mode="json", exclude_none=True)),
        ("agent", config.agent.model_dump(mode="json", exclude_none=True)),
    ]
    for name, values in sections:
        if not values:
            continue
        lines.append(f"[{name}]")
        for key, value in values.items():
            lines.append(f"{key} = {_toml_value(value)}")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def _toml_value(value) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, float):
        return repr(value)
    return json.dumps(str(value))
